# Generated by Django 6.0.5 on 2026-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Main title of the banner', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle of the banner', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Image for the banner', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to link the banner to', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the banner in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
