# Generated by Django 4.2.30 on 2026-05-11 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image/icon', null=True, upload_to='categories/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is category active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is product visible to customers')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/%Y/%m/')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Is this the primary image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
