# Generated by Django 6.0.5 on 2026-06-17 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Admin approval status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status'], name='products_pr_approva_e0c9d8_idx'),
        ),
    ]
